### ISSUE TITLE
error in first step of tutorial?

### ISSUE THREAD

**Issue by DoaneAS** [leipzig/SandwichesWithSnakemake#1]
I'm getting the following error.  Running python: 

Python 3.3.5 |Anaconda 2.2.0 (x86_64)| (default, Sep  2 2014, 13:57:31) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin

I'm running snakelike ok otherwise- not sure the issue.
The error:

(py3k)doanea@mlab0001:~/scripts/repos/SnakemakeMiniLesson$ snakemake -s basic.snake 
Provided cores: 1
Job counts:
    count   jobs
    2   peanut_butter_and_jelly_sandwich_recipe
    1   all
    3
rule peanut_butter_and_jelly_sandwich_recipe:
    input: kids/Jack, ingredients/jelly, ingredients/peanut_butter
    output: Jack.pbandj
Traceback (most recent call last):
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/**init**.py", line 365, in snakemake
    greedyness=greedyness)
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/workflow.py", line 419, in execute
    success = scheduler.schedule()
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/scheduler.py", line 205, in schedule
    self.run(job)
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/scheduler.py", line 217, in run
    error_callback=self._error)
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/executors.py", line 219, in run
    self.benchmark_repeats, self.workflow.linemaps)
  File "/Users/doanea/anaconda/lib/python2.7/site-packages/concurrent/futures/process.py", line 343, in submit
    self._adjust_process_count()
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/site-packages/snakemake/futures.py", line 36, in _adjust_process_count
    self._processes[p.pid] = p
TypeError: 'set' object does not support item assignment
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/doanea/anaconda/envs/py3k/lib/python3.3/multiprocessing/forking.py", line 115, in poll
    pid, sts = os.waitpid(self.pid, flag)

**Comment by DoaneAS** [comment]
was problem with python install on local
